name: hitched_backend
description: A Dart Frog server for the Hitched wedding app.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  dart_frog: ^1.0.0
  mysql_client: ^0.0.27
  json_annotation: ^4.9.0
  intl: ^0.19.0
  google_generative_ai: ^0.4.5

dev_dependencies:
  json_serializable: ^6.8.0
  mocktail: ^1.0.0
  test: ^1.19.0
